apiVersion: apps/v1
kind: Deployment
metadata:
  name: chesscoach-train-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chesscoach-train
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        tf-version.cloud-tpus.google.com: "2.3.1"
      labels:
        app: chesscoach-train
    spec:
      restartPolicy: Always
      volumes:
      - name: service-credentials
        secret:
          secretName: chesscoach-credentials
      containers:
      - name: chesscoach-train-container
        image: gcr.io/chesscoach/chesscoach-train:chesscoach1m_v3
        volumeMounts:
        - name: service-credentials
          mountPath: /var/secrets/google
          readOnly: true
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        resources:
          requests:
            cpu: 3
            memory: 30Gi
            cloud-tpus.google.com/v2: 8 # v2-8
            ephemeral-storage: 4Gi
          limits:
            cpu: 3.75
            memory: 30Gi
            cloud-tpus.google.com/v2: 8 # v2-8
            ephemeral-storage: 4Gi