###############################################################################
#                           Network configuration                             #
###############################################################################

[network]

training_network_name = "supervised9"
uci_network_name = "supervised9"

[[networks]]

    name = "supervised9"
    
    [networks.training]

    steps = 160_000
    num_games = 2_000_000
    games_path_training = "Games/Supervised"

    window_size_start = 2_000_000
    window_size_finish = 2_000_000

    [networks.training.learning_rate_schedule]

    steps = [0, 40_000, 80_000, 120_000]
    rates = [2.5e-2, 2.5e-3, 2.5e-4, 2.5e-5]

[[networks]]

    name = "selfplay3"

    [networks.training]

    validation_interval = 10
    checkpoint_interval = 100
    strength_test_interval = 500

[[networks]]

    name = "tiny1"

    [networks.training]

    batch_size = 512
    commentary_batch_size = 128
    steps = 100
    validation_interval = 10
    checkpoint_interval = 10
    strength_test_interval = 100
    num_games = 100

    [networks.self_play]

    num_workers = 1
    prediction_batch_size = 10

###############################################################################
#     Default training and self-play configuration. Networks can override.    #
###############################################################################

[training]

architecture = "conv2d"
batch_size = 512
commentary_batch_size = 256
steps = 1_400_000
pgn_interval = 100
validation_interval = 100
checkpoint_interval = 1000
strength_test_interval = 5000
num_games = 44_000_000
window_size_start = 31_428
window_size_finish = 1_000_000
value_loss_weight = 0.1
mcts_value_loss_weight = 0.015
policy_loss_weight = 1.0
reply_policy_loss_weight = 0.15
momentum = 0.9
vocabulary_filename = "vocabulary.txt"
games_path_training = "Games/Training"
games_path_validation = "Games/Validation"
commentary_path_training = "Data/Commentary"
commentary_path_validation = ""

[training.learning_rate_schedule]

steps = [0, 200_000, 600_000, 1_000_000]
rates = [1e-1, 1e-2, 1e-3, 1e-4]

[self_play]

num_workers = 4
prediction_batch_size = 256

num_sampling_moves = 30
max_moves = 512
num_simulations = 800

root_dirichlet_alpha = 0.3
root_exploration_fraction = 0.25

exploration_rate_base = 19652.0
exploration_rate_init = 1.25

###############################################################################
#                       Miscellaneous configuration                           #
###############################################################################

[prediction_cache]

size_gb = 8
max_ply = 24

[time_control]

safety_buffer_ms = 500
fraction_remaining = 20

[search]

mcts_parallelism = 16

[storage]

max_games_per_file = 2000

[paths]

networks = "Networks"
tensorboard = "TensorBoard"
logs = "Logs"
pgns = "Pgns"

###############################################################################