###############################################################################
#                           Network configuration                             #
###############################################################################

[network]

training_network_name = "selfplay1"
uci_network_name = "selfplay1"
role = "train|play"

[[networks]]

    name = "chesscoach1m"
    
    [networks.training]

    stages = [
        # Self-play
        { stage = "play", window_size_start = 6_000, window_size_finish = 200_000, num_games = 720_000 },

        # Train commentary, supervised and self-play, teacher
        { stage = "train_commentary", target = "teacher", type = "supervised" },
        { stage = "train", target = "teacher", type = "supervised", window_size_start = 2_000_000, window_size_finish = 2_000_000, num_games = 2_000_000 },
        { stage = "train", target = "teacher", type = "training", window_size_start = 6_000, window_size_finish = 200_000, num_games = 720_000 },
        { stage = "save", target = "teacher" },

        # Distill supervised and self-play to student
        { stage = "train", target = "student", type = "supervised", window_size_start = 2_000_000, window_size_finish = 2_000_000, num_games = 2_000_000 },
        { stage = "train", target = "student", type = "training", window_size_start = 6_000, window_size_finish = 200_000, num_games = 720_000 },
        { stage = "save", target = "student" },

        # Strength test (STS rating, etc.)
        { stage = "strength_test", target = "teacher" },
        { stage = "strength_test", target = "student" },
    ]

[[networks]]

    name = "supervised1"
    
    [networks.training]

    value_loss_weight = 0.1
    mcts_value_loss_weight = 0.015

    stages = [
        # Train supervised, teacher
        { stage = "train", target = "teacher", type = "supervised", window_size_start = 2_000_000, window_size_finish = 2_000_000, num_games = 2_000_000 },
        { stage = "save", target = "teacher" },

        # Strength test (STS rating, etc.)
        { stage = "strength_test", target = "teacher" },
    ]

[[networks]]

    name = "selfplay1"

    [networks.training]

    stages = [
        # Self-play
        { stage = "play", window_size_start = 12_000, window_size_finish = 400_000, num_games = 1_440_000 },

        # Train self-play, teacher then distill
        { stage = "train", target = "teacher", type = "training", window_size_start = 12_000, window_size_finish = 400_000, num_games = 1_440_000 },
        { stage = "save", target = "teacher" },
        { stage = "train", target = "student", type = "training", window_size_start = 12_000, window_size_finish = 400_000, num_games = 1_440_000 },
        { stage = "save", target = "student" },

        # Strength test (STS rating, etc.)
        { stage = "strength_test", target = "teacher" },
        { stage = "strength_test", target = "student" },
    ]

    games_path_training = "Games/SelfPlay"

[[networks]]

    name = "commentary1"
    
    [networks.training]

    stages = [
        # Train commentary, teacher
        { stage = "train_commentary", target = "teacher", type = "supervised" },
        { stage = "save", target = "teacher" },
    ]

    [networks.training.commentary_learning_rate_schedule]

    steps = [0, 60_000, 120_000, 180_000]
    rates = [2e-2, 2e-3, 2e-4, 2e-5]

[[networks]]

    name = "chesscoach-tiny1"

    [networks.training]

    steps = 100
    warmup_steps = 10

    validation_interval = 50
    checkpoint_interval = 50
    strength_test_interval = 100

    stages = [
        # Self-play
        { stage = "play", window_size_start = 50, window_size_finish = 100, num_games = 100 },

        # Train commentary, supervised and self-play, teacher
        { stage = "train_commentary", target = "teacher", type = "supervised" },
        { stage = "train", target = "teacher", type = "supervised", window_size_start = 100, window_size_finish = 100, num_games = 100 },
        { stage = "train", target = "teacher", type = "training", window_size_start = 50, window_size_finish = 100, num_games = 100 },
        { stage = "save", target = "teacher" },

        # Distill supervised and self-play to student
        { stage = "train", target = "student", type = "supervised", window_size_start = 100, window_size_finish = 100, num_games = 100 },
        { stage = "train", target = "student", type = "training", window_size_start = 50, window_size_finish = 100, num_games = 100 },
        { stage = "save", target = "student" },

        # Strength test (STS rating, etc.)
        { stage = "strength_test", target = "teacher" },
        { stage = "strength_test", target = "student" },
    ]

    [networks.self_play]

    num_workers = 2
    prediction_batch_size = 50

[[networks]]

    name = "supervised-tiny1"
    
    [networks.training]

    value_loss_weight = 0.1
    mcts_value_loss_weight = 0.015

    steps = 100
    warmup_steps = 10

    validation_interval = 50
    checkpoint_interval = 50
    strength_test_interval = 100

    stages = [
        # Train supervised, teacher
        { stage = "train", target = "teacher", type = "supervised", window_size_start = 100, window_size_finish = 100, num_games = 100 },
        { stage = "save", target = "teacher" },

        # Strength test (STS rating, etc.)
        { stage = "strength_test", target = "teacher" },
    ]

[[networks]]

    name = "selfplay-tiny1"

    [networks.training]

    steps = 100
    warmup_steps = 10

    validation_interval = 50
    checkpoint_interval = 50
    strength_test_interval = 100

    stages = [
        # Self-play
        { stage = "play", window_size_start = 50, window_size_finish = 100, num_games = 100 },

        # Train self-play, teacher then distill
        { stage = "train", target = "teacher", type = "training", window_size_start = 50, window_size_finish = 100, num_games = 100 },
        { stage = "save", target = "teacher" },
        { stage = "train", target = "student", type = "training", window_size_start = 50, window_size_finish = 100, num_games = 100 },
        { stage = "save", target = "student" },

        # Strength test (STS rating, etc.)
        { stage = "strength_test", target = "teacher" },
        { stage = "strength_test", target = "student" },
    ]

    [networks.self_play]

    num_workers = 2
    prediction_batch_size = 50

[[networks]]

    name = "commentary-tiny1"
    
    [networks.training]

    steps = 100
    warmup_steps = 10

    validation_interval = 50
    checkpoint_interval = 50
    strength_test_interval = 100

    stages = [
        # Train commentary, teacher
        { stage = "train_commentary", target = "teacher", type = "supervised" },
        { stage = "save", target = "teacher" },
    ]

    [networks.training.commentary_learning_rate_schedule]

    steps = [0, 60_000, 120_000, 180_000]
    rates = [2e-2, 2e-3, 2e-4, 2e-5]

[[networks]]

    name = "benchmark1"

    [networks.training]

    stages = [
        # Self-play
        { stage = "play", window_size_start = 720_000, window_size_finish = 720_000, num_games = 720_000 },
    ]

    games_path_training = "Games/Benchmark"

    # NOTE: Still need to (a) turn off prediction cache if network untrained, (b) turn off uniform predictions if steps <= 0

###############################################################################
#     Default training and self-play configuration. Networks can override.    #
###############################################################################

[training]

architecture = "conv2d"
batch_size = 512
commentary_batch_size = 256
steps = 240_000
warmup_steps = 1000
pgn_interval = 100
validation_interval = 200
checkpoint_interval = 2000
strength_test_interval = 10000
value_loss_weight = 1.0
mcts_value_loss_weight = 0.05
policy_loss_weight = 1.0
reply_policy_loss_weight = 0.05
momentum = 0.9
vocabulary_filename = "vocabulary.txt"
games_path_supervised = "Games/Supervised"
games_path_training = "Games/Training"
games_path_validation = "Games/Validation"
commentary_path_supervised = "Commentary/Supervised"
commentary_path_training = ""
commentary_path_validation = ""
wait_milliseconds = 300_000 # Check on Google Storage every 5 minutes when waiting for other machines.
stages = []

[training.learning_rate_schedule]

steps = [0, 60_000, 120_000, 180_000]
rates = [2.5e-2, 2.5e-3, 2.5e-4, 2.5e-5]

[training.commentary_learning_rate_schedule]

steps = [0, 60_000, 120_000, 180_000]
rates = [2e-4, 2e-5, 2e-6, 2e-7]

[self_play]

num_workers = 8
prediction_batch_size = 512

num_sampling_moves = 30
max_moves = 512
num_simulations = 800

root_dirichlet_alpha = 0.3
root_exploration_fraction = 0.25

exploration_rate_base = 19652.0
exploration_rate_init = 1.25

network_update_check_interval_seconds = 300.0
wait_for_updated_network = false

###############################################################################
#                       Miscellaneous configuration                           #
###############################################################################

[prediction_cache]

size_gibibytes = 8
max_ply = 24

[time_control]

safety_buffer_milliseconds = 500
fraction_remaining = 20

[search]

mcts_parallelism = 16
gui_update_interval_nodes = 1000

[storage]

games_per_chunk = 2000

[paths]

# With the below config, a network may be saved to "gs://chesscoach/ChessCoach/Networks/network_000001000".
gcloud_bucket = "chesscoach"
gcloud_prefix = "ChessCoach"

networks = "Networks"
tensorboard = "TensorBoard"
logs = "Logs"
pgns = "Pgns"

strength_test_marker_prefix = "StrengthTestComplete"

###############################################################################