###############################################################################
#                           Network configuration                             #
###############################################################################

[network]

training_network_name = "curriculum2"
uci_network_name = "curriculum2"

[[networks]]

    name = "curriculum2"

    [networks.training]

    steps = 63000
    num_games = 0
    window_size = 10_000_000
    games_path_training = "Games/Supervised"

    [networks.training.learning_rate_schedule]

    steps = [0, 15_000, 30_000, 50_000]
    rates = [1e-1, 1e-2, 1e-3, 1e-4]

[[networks]]

    name = "supervised5"

    [networks.training]

    steps = 63000
    num_games = 0
    window_size = 10_000_000
    games_path_training = "Games/Supervised"

    [networks.training.learning_rate_schedule]

    steps = [0, 15_000, 30_000, 50_000]
    rates = [1e-1, 1e-2, 1e-3, 1e-4]

[[networks]]

    name = "selfplay3"

    [networks.training]

    validation_interval = 10
    checkpoint_interval = 100
    strength_test_interval = 500

[[networks]]

    name = "tiny1"

    [networks.training]

    batch_size = 512
    steps = 100
    validation_interval = 10
    checkpoint_interval = 10
    strength_test_interval = 100
    num_games = 100

    [networks.self_play]

    num_workers = 1
    prediction_batch_size = 10

###############################################################################
#     Default training and self-play configuration. Networks can override.    #
###############################################################################

[training]

architecture = "conv2d"
batch_size = 2048
steps = 1_400_000
pgn_interval = 100
validation_interval = 100
checkpoint_interval = 1000
strength_test_interval = 5000
num_games = 44_000_000
window_size = 1_000_000
value_loss_weight = 0.1
policy_loss_weight = 1.0
reply_policy_loss_weight = 0.15
momentum = 0.9
games_path_training = "Games/Training"
games_path_validation = "Games/Validation"

[training.learning_rate_schedule]

steps = [0, 200_000, 600_000, 1_000_000]
rates = [1e-1, 1e-2, 1e-3, 1e-4]

[self_play]

num_workers = 4
prediction_batch_size = 128

num_sampling_moves = 30
max_moves = 512
num_simulations = 800

root_dirichlet_alpha = 0.3
root_exploration_fraction = 0.25

exploration_rate_base = 19652.0
exploration_rate_init = 1.25

###############################################################################
#                       Miscellaneous configuration                           #
###############################################################################

[prediction_cache]

size_gb = 8
max_ply = 24

[time_control]

safety_buffer_ms = 500
fraction_remaining = 20

[search]

mcts_parallelism = 16

[storage]

max_games_per_file = 2000

[paths]

networks = "Networks"
tensorboard = "TensorBoard"
logs = "Logs"
pgns = "Pgns"

###############################################################################